<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class UserProfilesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('user_profiles')->insert([
            [
                'user_id' => 1,
                'first_name_ja' => '悠登',
                'last_name_ja' => '宮崎',
                'first_name_kana' => 'ユウト',
                'last_name_kana' => 'ミヤザキ',
                'first_name_en' => 'yuto',
                'last_name_en' => 'miyazaki',
                'graduation_year' => 2021,
                'grade' => null,
                'position_id' => 1,
                'prefecture_id' => 6,
                'alma_mater' => '山形県羽黒高等学校',
                'achievement' => '2016ハイスクールジャパンカップ ダブルス 準優勝',
            ],
            [
                'user_id' => 2,
                'first_name_ja' => '信治',
                'last_name_ja' => '坂本',
                'first_name_kana' => 'シンジ',
                'last_name_kana' => 'サカモト',
                'first_name_en' => 'shinji',
                'last_name_en' => 'sakamoto',
                'graduation_year' => 2021,
                'grade' => null,
                'position_id' => 2,
                'prefecture_id' => 1,
                'alma_mater' => '北海道科学大学高等学校',
                'achievement' => '2016全日本高校選抜 3位',
            ],
            [
                'user_id' => 3,
                'first_name_ja' => '雅人',
                'last_name_ja' => '田邉',
                'first_name_kana' => 'マサト',
                'last_name_kana' => 'タナベ',
                'first_name_en' => 'masato',
                'last_name_en' => 'tanabe',
                'graduation_year' => 2021,
                'grade' => null,
                'position_id' => 2,
                'prefecture_id' => 7,
                'alma_mater' => '三重県三重高等学校',
                'achievement' => '2016岩手国体少年男子 優勝',
            ],
            [
                'user_id' => 4,
                'first_name_ja' => '利貴',
                'last_name_ja' => '斎藤',
                'first_name_kana' => 'リキ',
                'last_name_kana' => 'サイトウ',
                'first_name_en' => 'riki',
                'last_name_en' => 'saito',
                'graduation_year' => 2021,
                'grade' => null,
                'position_id' => 1,
                'prefecture_id' => 12,
                'alma_mater' => '千葉県昭和学院高等学校',
                'achievement' => '2016ハイスクールジャパンカップ ダブルス ベスト8',
            ],
            [
                'user_id' => 5,
                'first_name_ja' => '辰哉',
                'last_name_ja' => '佐藤',
                'first_name_kana' => 'タツヤ',
                'last_name_kana' => 'サトウ',
                'first_name_en' => 'tatsuya',
                'last_name_en' => 'sato',
                'graduation_year' => null,
                'grade' => 4,
                'position_id' => 1,
                'prefecture_id' => 40,
                'alma_mater' => '香川県尽誠学園高等学校',
                'achievement' => '2016ハイスクールジャパンカップ ダブルス 3位',
            ],
            [
                'user_id' => 6,
                'first_name_ja' => '章',
                'last_name_ja' => '丸山',
                'first_name_kana' => 'アキラ',
                'last_name_kana' => 'マルヤマ',
                'first_name_en' => 'akira',
                'last_name_en' => 'maruyama',
                'graduation_year' => null,
                'grade' => 4,
                'position_id' => 1,
                'prefecture_id' => 34,
                'alma_mater' => '広島県尾道高等学校',
                'achievement' => '2017ハイスクールジャパンカップ ダブルス 3位',
            ],
            [
                'user_id' => 7,
                'first_name_ja' => '迅',
                'last_name_ja' => '濱田',
                'first_name_kana' => 'ジン',
                'last_name_kana' => 'ハマダ',
                'first_name_en' => 'jin',
                'last_name_en' => 'hamada',
                'graduation_year' => null,
                'grade' => 4,
                'position_id' => 2,
                'prefecture_id' => 30,
                'alma_mater' => '和歌山県和歌山北高等学校',
                'achievement' => '2011全日本小学生ソフトテニス選手権大会 優勝',
            ],
            [
                'user_id' => 8,
                'first_name_ja' => '誠人',
                'last_name_ja' => '橋本',
                'first_name_kana' => 'マサト',
                'last_name_kana' => 'ハシモト',
                'first_name_en' => 'masato',
                'last_name_en' => 'hashimoto',
                'graduation_year' => null,
                'grade' => 4,
                'position_id' => 2,
                'prefecture_id' => 8,
                'alma_mater' => '千葉県昭和学院高等学校',
                'achievement' => '2016ハイスクールジャパンカップ ダブルス ベスト8',
            ],
            [
                'user_id' => 9,
                'first_name_ja' => '啓吾',
                'last_name_ja' => '伊藤',
                'first_name_kana' => 'ケイゴ',
                'last_name_kana' => 'イトウ',
                'first_name_en' => 'keigo',
                'last_name_en' => 'ito',
                'graduation_year' => null,
                'grade' => 4,
                'position_id' => 2,
                'prefecture_id' => 8,
                'alma_mater' => '千葉県木更津総合高等学校',
                'achievement' => '2017福島インターハイ 団体戦 3位',
            ],
            [
                'user_id' => 10,
                'first_name_ja' => '民生',
                'last_name_ja' => '林',
                'first_name_kana' => 'タミオ',
                'last_name_kana' => 'ハヤシ',
                'first_name_en' => 'tamio',
                'last_name_en' => 'hayashi',
                'graduation_year' => null,
                'grade' => 4,
                'position_id' => 1,
                'prefecture_id' => 7,
                'alma_mater' => '宮城県東北高等学校',
                'achievement' => '2016岡山インターハイ 団体戦 優勝',
            ],
            [
                'user_id' => 11,
                'first_name_ja' => '優希',
                'last_name_ja' => '三枝',
                'first_name_kana' => 'ユウキ',
                'last_name_kana' => 'サエグサ',
                'first_name_en' => 'yuki',
                'last_name_en' => 'saegusa',
                'graduation_year' => null,
                'grade' => 4,
                'position_id' => 1,
                'prefecture_id' => 22,
                'alma_mater' => '静岡県加藤学園高等学校',
                'achievement' => '2017 インターハイ出場',
            ],
            [
                'user_id' => 12,
                'first_name_ja' => '笑',
                'last_name_ja' => '旭',
                'first_name_kana' => 'エム',
                'last_name_kana' => 'アサヒ',
                'first_name_en' => 'emu',
                'last_name_en' => 'asahi',
                'graduation_year' => null,
                'grade' => 3,
                'position_id' => 1,
                'prefecture_id' => 6,
                'alma_mater' => '山形県羽黒高等学校',
                'achievement' => '2018三重インターハイ 団体戦 準優勝',
            ],
            [
                'user_id' => 13,
                'first_name_ja' => '祐也',
                'last_name_ja' => '古山',
                'first_name_kana' => 'ユウヤ',
                'last_name_kana' => 'コヤマ',
                'first_name_en' => 'yuya',
                'last_name_en' => 'koyama',
                'graduation_year' => null,
                'grade' => 3,
                'position_id' => 2,
                'prefecture_id' => 2,
                'alma_mater' => '宮城県東北高等学校',
                'achievement' => '2018三重インターハイ 第9位',
            ],
            [
                'user_id' => 14,
                'first_name_ja' => '遥斗',
                'last_name_ja' => '檜山',
                'first_name_kana' => 'ハルト',
                'last_name_kana' => 'ヒヤマ',
                'first_name_en' => 'haruto',
                'last_name_en' => 'hiyama',
                'graduation_year' => null,
                'grade' => 3,
                'position_id' => 2,
                'prefecture_id' => 7,
                'alma_mater' => '宮城県東北高等学校',
                'achievement' => '2018全日本高校選抜 優勝',
            ],
            [
                'user_id' => 15,
                'first_name_ja' => '大輝',
                'last_name_ja' => '藤田',
                'first_name_kana' => 'ダイキ',
                'last_name_kana' => 'フジタ',
                'first_name_en' => 'daiki',
                'last_name_en' => 'fujita',
                'graduation_year' => null,
                'grade' => 3,
                'position_id' => 1,
                'prefecture_id' => 1,
                'alma_mater' => '北海道とわの森三愛高等学校',
                'achievement' => '2018福井国体少年男子 準優勝',
            ],
            [
                'user_id' => 16,
                'first_name_ja' => '孝耶',
                'last_name_ja' => '岡部',
                'first_name_kana' => 'タカヤ',
                'last_name_kana' => 'オカベ',
                'first_name_en' => 'takaya',
                'last_name_en' => 'okabe',
                'graduation_year' => null,
                'grade' => 3,
                'position_id' => 1,
                'prefecture_id' => 22,
                'alma_mater' => '静岡県富士宮北高等学校',
                'achievement' => '2018ハイスクールジャパンカップ シングルス 準優勝',
            ],
            [
                'user_id' => 17,
                'first_name_ja' => '柊也',
                'last_name_ja' => '星',
                'first_name_kana' => 'シュウヤ',
                'last_name_kana' => 'ホシ',
                'first_name_en' => 'shuya',
                'last_name_en' => 'hoshi',
                'graduation_year' => null,
                'grade' => 2,
                'position_id' => 2,
                'prefecture_id' => 4,
                'alma_mater' => '宮城県東北高等学校',
                'achievement' => '2019全日本高校選抜 準優勝',
            ],
            [
                'user_id' => 18,
                'first_name_ja' => '龍生',
                'last_name_ja' => '菊池',
                'first_name_kana' => 'リュウセイ',
                'last_name_kana' => 'キクチ',
                'first_name_en' => 'ryusei',
                'last_name_en' => 'kikuti',
                'graduation_year' => null,
                'grade' => 2,
                'position_id' => 1,
                'prefecture_id' => 8,
                'alma_mater' => '茨城県霞ヶ浦高等学校',
                'achievement' => '2019ハイスクールジャパンカップ ダブルス 準優勝',
            ],
            [
                'user_id' => 19,
                'first_name_ja' => '匡紀',
                'last_name_ja' => '伊藤',
                'first_name_kana' => 'マサキ',
                'last_name_kana' => 'イトウ',
                'first_name_en' => 'masaki',
                'last_name_en' => 'ito',
                'graduation_year' => null,
                'grade' => 2,
                'position_id' => 1,
                'prefecture_id' => 22,
                'alma_mater' => '三重県三重高等学校',
                'achievement' => '2019全日本高校選抜 ベスト8',
            ],
            [
                'user_id' => 20,
                'first_name_ja' => '怜',
                'last_name_ja' => '白鳥',
                'first_name_kana' => 'リョウ',
                'last_name_kana' => 'シロトリ',
                'first_name_en' => 'ryo',
                'last_name_en' => 'shirotori',
                'graduation_year' => null,
                'grade' => 2,
                'position_id' => 2,
                'prefecture_id' => 4,
                'alma_mater' => '宮城県東北高等学校',
                'achievement' => '2019全日本高校選抜 準優勝',
            ],
            [
                'user_id' => 21,
                'first_name_ja' => '駿人',
                'last_name_ja' => '西田',
                'first_name_kana' => 'ハヤト',
                'last_name_kana' => 'ニシダ',
                'first_name_en' => 'hayato',
                'last_name_en' => 'nisida',
                'graduation_year' => null,
                'grade' => 2,
                'position_id' => 2,
                'prefecture_id' => 12,
                'alma_mater' => '奈良県高田商業高等学校',
                'achievement' => '2019茨城国体少年男子 優勝',
            ],
            [
                'user_id' => 22,
                'first_name_ja' => '優太',
                'last_name_ja' => '入澤',
                'first_name_kana' => 'ユウタ',
                'last_name_kana' => 'イリサワ',
                'first_name_en' => 'yuta',
                'last_name_en' => 'irisawa',
                'graduation_year' => null,
                'grade' => 2,
                'position_id' => 2,
                'prefecture_id' => 11,
                'alma_mater' => '埼玉県立川越高等学校',
                'achievement' => '2019インターハイ個人戦 出場',
            ],
            [
                'user_id' => 23,
                'first_name_ja' => '弘',
                'last_name_ja' => '田中',
                'first_name_kana' => 'ヒロシ',
                'last_name_kana' => 'タナカ',
                'first_name_en' => 'hiroshi',
                'last_name_en' => 'tanaka',
                'graduation_year' => 1976,
                'grade' => null,
                'position_id' => 2,
                'prefecture_id' => null,
                'alma_mater' => '中央大学附属高校',
                'achievement' => 'アジア選手権・東アジア競技大会 日本代表優勝監督',
            ],
            [
                'user_id' => 24,
                'first_name_ja' => '直哉',
                'last_name_ja' => '高橋',
                'first_name_kana' => 'ナオヤ',
                'last_name_kana' => 'タカハシ',
                'first_name_en' => 'naoya',
                'last_name_en' => 'takahashi',
                'graduation_year' => 1989,
                'grade' => null,
                'position_id' => null,
                'prefecture_id' => null,
                'alma_mater' => null,
                'achievement' => '中央大学大学院法務研究科教授',
            ],
            [
                'user_id' => 25,
                'first_name_ja' => '秊夫',
                'last_name_ja' => '田中',
                'first_name_kana' => 'トシオ',
                'last_name_kana' => 'タナカ',
                'first_name_en' => 'toshio',
                'last_name_en' => 'tanaka',
                'graduation_year' => 1956,
                'grade' => null,
                'position_id' => null,
                'prefecture_id' => null,
                'alma_mater' => null,
                'achievement' => null,
            ],
            [
                'user_id' => 26,
                'first_name_ja' => '忠佳',
                'last_name_ja' => '畑中',
                'first_name_kana' => 'タダヨシ',
                'last_name_kana' => 'ハタナカ',
                'first_name_en' => 'tadayoshi',
                'last_name_en' => 'hatanaka',
                'graduation_year' => 1959,
                'grade' => null,
                'position_id' => null,
                'prefecture_id' => null,
                'alma_mater' => null,
                'achievement' => null,
            ],
            [
                'user_id' => 27,
                'first_name_ja' => '雅哉',
                'last_name_ja' => '松山',
                'first_name_kana' => 'マサヤ',
                'last_name_kana' => 'マツヤマ',
                'first_name_en' => 'masaya',
                'last_name_en' => 'matsuyama',
                'graduation_year' => 1960,
                'grade' => null,
                'position_id' => null,
                'prefecture_id' => null,
                'alma_mater' => null,
                'achievement' => null,
            ],
            [
                'user_id' => 28,
                'first_name_ja' => '武徳',
                'last_name_ja' => '楠',
                'first_name_kana' => 'タケノリ',
                'last_name_kana' => 'クスノキ',
                'first_name_en' => 'takenori',
                'last_name_en' => 'kusunoki',
                'graduation_year' => 1962,
                'grade' => null,
                'position_id' => null,
                'prefecture_id' => null,
                'alma_mater' => null,
                'achievement' => null,
            ],
            [
                'user_id' => 29,
                'first_name_ja' => '幸夫',
                'last_name_ja' => '篭田',
                'first_name_kana' => 'ユキオ',
                'last_name_kana' => 'カゴタ',
                'first_name_en' => 'yukio',
                'last_name_en' => 'kagota',
                'graduation_year' => 1963,
                'grade' => null,
                'position_id' => null,
                'prefecture_id' => null,
                'alma_mater' => null,
                'achievement' => null,
            ],
            [
                'user_id' => 30,
                'first_name_ja' => '有信',
                'last_name_ja' => '木本',
                'first_name_kana' => 'アリノブ',
                'last_name_kana' => 'キモト',
                'first_name_en' => 'arinobu',
                'last_name_en' => 'kimoto',
                'graduation_year' => 1963,
                'grade' => null,
                'position_id' => null,
                'prefecture_id' => null,
                'alma_mater' => null,
                'achievement' => null,
            ],
            [
                'user_id' => 31,
                'first_name_ja' => '満',
                'last_name_ja' => '竹島',
                'first_name_kana' => 'ミツル',
                'last_name_kana' => 'タケシマ',
                'first_name_en' => 'mitsuru',
                'last_name_en' => 'takeshima',
                'graduation_year' => 1968,
                'grade' => null,
                'position_id' => null,
                'prefecture_id' => null,
                'alma_mater' => null,
                'achievement' => null,
            ],
            [
                'user_id' => 32,
                'first_name_ja' => '善裕',
                'last_name_ja' => '土屋',
                'first_name_kana' => 'ヨシヒロ',
                'last_name_kana' => 'ツチヤ',
                'first_name_en' => 'yoshihiro',
                'last_name_en' => 'tsutiya',
                'graduation_year' => 1970,
                'grade' => null,
                'position_id' => null,
                'prefecture_id' => null,
                'alma_mater' => null,
                'achievement' => null,
            ],
            [
                'user_id' => 33,
                'first_name_ja' => '猛夫',
                'last_name_ja' => '佐藤',
                'first_name_kana' => 'タケオ',
                'last_name_kana' => 'サトウ',
                'first_name_en' => 'takeo',
                'last_name_en' => 'sato',
                'graduation_year' => 1975,
                'grade' => null,
                'position_id' => null,
                'prefecture_id' => null,
                'alma_mater' => null,
                'achievement' => null,
            ],
            [
                'user_id' => 34,
                'first_name_ja' => '晋',
                'last_name_ja' => '大江',
                'first_name_kana' => 'ススム',
                'last_name_kana' => 'オオエ',
                'first_name_en' => 'susumu',
                'last_name_en' => 'ooe',
                'graduation_year' => 1975,
                'grade' => null,
                'position_id' => null,
                'prefecture_id' => null,
                'alma_mater' => null,
                'achievement' => null,
            ],
            [
                'user_id' => 35,
                'first_name_ja' => '博之',
                'last_name_ja' => '村上',
                'first_name_kana' => 'ヒロユキ',
                'last_name_kana' => 'ムラカミ',
                'first_name_en' => 'hiroyuki',
                'last_name_en' => 'murakami',
                'graduation_year' => 1977,
                'grade' => null,
                'position_id' => null,
                'prefecture_id' => null,
                'alma_mater' => null,
                'achievement' => null,
            ],
            [
                'user_id' => 36,
                'first_name_ja' => '宏一',
                'last_name_ja' => '武田',
                'first_name_kana' => 'コウイチ',
                'last_name_kana' => 'タケダ',
                'first_name_en' => 'kouichi',
                'last_name_en' => 'takeda',
                'graduation_year' => 1978,
                'grade' => null,
                'position_id' => null,
                'prefecture_id' => null,
                'alma_mater' => null,
                'achievement' => null,
            ],
            [
                'user_id' => 37,
                'first_name_ja' => '正美',
                'last_name_ja' => '曽根田',
                'first_name_kana' => 'マサミ',
                'last_name_kana' => 'ソネダ',
                'first_name_en' => 'masami',
                'last_name_en' => 'soneda',
                'graduation_year' => 1968,
                'grade' => null,
                'position_id' => null,
                'prefecture_id' => null,
                'alma_mater' => null,
                'achievement' => null,
            ],
            [
                'user_id' => 38,
                'first_name_ja' => '正博',
                'last_name_ja' => '芹澤',
                'first_name_kana' => 'マサヒロ',
                'last_name_kana' => 'セリザワ',
                'first_name_en' => 'masahiro',
                'last_name_en' => 'serizawa',
                'graduation_year' => 1971,
                'grade' => null,
                'position_id' => null,
                'prefecture_id' => null,
                'alma_mater' => null,
                'achievement' => null,
            ],
            [
                'user_id' => 39,
                'first_name_ja' => '正輝',
                'last_name_ja' => '池端',
                'first_name_kana' => 'マサキ',
                'last_name_kana' => 'イケハタ',
                'first_name_en' => 'masaki',
                'last_name_en' => 'ikehata',
                'graduation_year' => 1974,
                'grade' => null,
                'position_id' => null,
                'prefecture_id' => null,
                'alma_mater' => null,
                'achievement' => null,
            ],
            [
                'user_id' => 40,
                'first_name_ja' => '美代子',
                'last_name_ja' => '松本',
                'first_name_kana' => 'ミヨコ',
                'last_name_kana' => 'マツモト',
                'first_name_en' => 'miyoko',
                'last_name_en' => 'matsumoto',
                'graduation_year' => 1975,
                'grade' => null,
                'position_id' => null,
                'prefecture_id' => null,
                'alma_mater' => null,
                'achievement' => null,
            ],
            [
                'user_id' => 41,
                'first_name_ja' => '耕嗣',
                'last_name_ja' => '小田',
                'first_name_kana' => 'コウジ',
                'last_name_kana' => 'オダ',
                'first_name_en' => 'kouji',
                'last_name_en' => 'oda',
                'graduation_year' => 1977,
                'grade' => null,
                'position_id' => null,
                'prefecture_id' => null,
                'alma_mater' => null,
                'achievement' => null,
            ],
            [
                'user_id' => 42,
                'first_name_ja' => '斉',
                'last_name_ja' => '永田',
                'first_name_kana' => 'セイ',
                'last_name_kana' => 'ナガタ',
                'first_name_en' => 'sei',
                'last_name_en' => 'nagata',
                'graduation_year' => 1981,
                'grade' => null,
                'position_id' => null,
                'prefecture_id' => null,
                'alma_mater' => null,
                'achievement' => null,
            ],
            [
                'user_id' => 43,
                'first_name_ja' => '均',
                'last_name_ja' => '伊藤',
                'first_name_kana' => 'ヒトシ',
                'last_name_kana' => 'イトウ',
                'first_name_en' => 'hitoshi',
                'last_name_en' => 'ito',
                'graduation_year' => 1985,
                'grade' => null,
                'position_id' => null,
                'prefecture_id' => null,
                'alma_mater' => null,
                'achievement' => null,
            ],
            [
                'user_id' => 44,
                'first_name_ja' => '清',
                'last_name_ja' => '塩出',
                'first_name_kana' => 'キヨシ',
                'last_name_kana' => 'シオデ',
                'first_name_en' => 'kiyoshi',
                'last_name_en' => 'shiode',
                'graduation_year' => 1986,
                'grade' => null,
                'position_id' => null,
                'prefecture_id' => null,
                'alma_mater' => null,
                'achievement' => null,
            ],
            [
                'user_id' => 45,
                'first_name_ja' => '俊彦',
                'last_name_ja' => '大門',
                'first_name_kana' => 'トシヒコ',
                'last_name_kana' => 'ダイモン',
                'first_name_en' => 'toshihiko',
                'last_name_en' => 'daimon',
                'graduation_year' => 2000,
                'grade' => null,
                'position_id' => null,
                'prefecture_id' => null,
                'alma_mater' => null,
                'achievement' => null,
            ],
            [
                'user_id' => 46,
                'first_name_ja' => '陽介',
                'last_name_ja' => '土井内',
                'first_name_kana' => 'ヨウスケ',
                'last_name_kana' => 'ドイウチ',
                'first_name_en' => 'yousuke',
                'last_name_en' => 'doiuchi',
                'graduation_year' => 2005,
                'grade' => null,
                'position_id' => null,
                'prefecture_id' => null,
                'alma_mater' => null,
                'achievement' => null,
            ],
            [
                'user_id' => 47,
                'first_name_ja' => '岳',
                'last_name_ja' => '大川戸',
                'first_name_kana' => 'ガク',
                'last_name_kana' => 'オオカワト',
                'first_name_en' => 'gaku',
                'last_name_en' => 'ookawato',
                'graduation_year' => 2009,
                'grade' => null,
                'position_id' => null,
                'prefecture_id' => null,
                'alma_mater' => null,
                'achievement' => null,
            ],
            [
                'user_id' => 48,
                'first_name_ja' => '美弘',
                'last_name_ja' => '山崎',
                'first_name_kana' => 'ミヒロ',
                'last_name_kana' => 'ヤマザキ',
                'first_name_en' => 'mihiro',
                'last_name_en' => 'yamazaki',
                'graduation_year' => 1978,
                'grade' => null,
                'position_id' => null,
                'prefecture_id' => null,
                'alma_mater' => null,
                'achievement' => null,
            ],
            [
                'user_id' => 49,
                'first_name_ja' => '高司',
                'last_name_ja' => '西山',
                'first_name_kana' => 'タカシ',
                'last_name_kana' => 'ニシヤマ',
                'first_name_en' => 'takashi',
                'last_name_en' => 'nishiyama',
                'graduation_year' => 1980,
                'grade' => null,
                'position_id' => null,
                'prefecture_id' => null,
                'alma_mater' => null,
                'achievement' => null,
            ],
            [
                'user_id' => 50,
                'first_name_ja' => '成生',
                'last_name_ja' => '中堀',
                'first_name_kana' => 'シゲオ',
                'last_name_kana' => 'ナカホリ',
                'first_name_en' => 'sigeo',
                'last_name_en' => 'nakahori',
                'graduation_year' => 1994,
                'grade' => null,
                'position_id' => 1,
                'prefecture_id' => 12,
                'alma_mater' => null,
                'achievement' => '第16回世界選手権大会 国別対抗戦 優勝（監督）',
            ],
            [
                'user_id' => 51,
                'first_name_ja' => '大明',
                'last_name_ja' => '丸中',
                'first_name_kana' => 'タイメイ',
                'last_name_kana' => 'マルナカ',
                'first_name_en' => 'taimei',
                'last_name_en' => 'marunaka',
                'graduation_year' => 2016,
                'grade' => null,
                'position_id' => 1,
                'prefecture_id' => 4,
                'alma_mater' => '宮城県東北高等学校',
                'achievement' => '第16回世界選手権大会 国別対抗戦 優勝',
            ],
            [
                'user_id' => 52,
                'first_name_ja' => '琢己',
                'last_name_ja' => '鈴木',
                'first_name_kana' => 'タクミ',
                'last_name_kana' => 'スズキ',
                'first_name_en' => 'takumi',
                'last_name_en' => 'suzuki',
                'graduation_year' => 2016,
                'grade' => null,
                'position_id' => 2,
                'prefecture_id' => 7,
                'alma_mater' => '宮城県東北高等学校',
                'achievement' => '第16回世界選手権大会 国別対抗戦 優勝',
            ],
            [
                'user_id' => 53,
                'first_name_ja' => '孝則',
                'last_name_ja' => '北村',
                'first_name_kana' => 'タカノリ',
                'last_name_kana' => 'キタムラ',
                'first_name_en' => 'takanori',
                'last_name_en' => 'kitamura',
                'graduation_year' => 1965,
                'grade' => null,
                'position_id' => null,
                'prefecture_id' => null,
                'alma_mater' => null,
                'achievement' => null,
            ],
            [
                'user_id' => 54,
                'first_name_ja' => '雅史',
                'last_name_ja' => '新子',
                'first_name_kana' => 'マサシ',
                'last_name_kana' => 'アタラシ',
                'first_name_en' => 'masashi',
                'last_name_en' => 'atarashi',
                'graduation_year' => 1980,
                'grade' => null,
                'position_id' => null,
                'prefecture_id' => null,
                'alma_mater' => null,
                'achievement' => null,
            ],
            [
                'user_id' => 55,
                'first_name_ja' => '康裕',
                'last_name_ja' => '早川',
                'first_name_kana' => 'ヤスヒロ',
                'last_name_kana' => 'ハヤカワ',
                'first_name_en' => 'yasuhiro',
                'last_name_en' => 'hayakawa',
                'graduation_year' => 1991,
                'grade' => null,
                'position_id' => null,
                'prefecture_id' => null,
                'alma_mater' => null,
                'achievement' => null,
            ],
            [
                'user_id' => 56,
                'first_name_ja' => '惣一',
                'last_name_ja' => '西田',
                'first_name_kana' => 'ソウイチ',
                'last_name_kana' => 'ニシダ',
                'first_name_en' => 'souichi',
                'last_name_en' => 'nishida',
                'graduation_year' => 1999,
                'grade' => null,
                'position_id' => null,
                'prefecture_id' => null,
                'alma_mater' => null,
                'achievement' => null,
            ],
            [
                'user_id' => 57,
                'first_name_ja' => '貴徳',
                'last_name_ja' => '新田',
                'first_name_kana' => 'タカノリ',
                'last_name_kana' => 'ニッタ',
                'first_name_en' => 'takanori',
                'last_name_en' => 'nitta',
                'graduation_year' => 2001,
                'grade' => null,
                'position_id' => null,
                'prefecture_id' => null,
                'alma_mater' => null,
                'achievement' => null,
            ],
            [
                'user_id' => 58,
                'first_name_ja' => '幸寿',
                'last_name_ja' => '須永',
                'first_name_kana' => 'ユキトシ',
                'last_name_kana' => 'スナガ',
                'first_name_en' => 'yukitoshi',
                'last_name_en' => 'sunaga',
                'graduation_year' => 2014,
                'grade' => null,
                'position_id' => null,
                'prefecture_id' => null,
                'alma_mater' => null,
                'achievement' => null,
            ],
            [
                'user_id' => 59,
                'first_name_ja' => '将義',
                'last_name_ja' => '十津川',
                'first_name_kana' => 'マサヨシ',
                'last_name_kana' => 'トツカワ',
                'first_name_en' => 'masayoshi',
                'last_name_en' => 'totsukawa',
                'graduation_year' => 2016,
                'grade' => null,
                'position_id' => null,
                'prefecture_id' => null,
                'alma_mater' => null,
                'achievement' => null,
            ],
            [
                'user_id' => 60,
                'first_name_ja' => '幸大',
                'last_name_ja' => '岩本',
                'first_name_kana' => 'コウダイ',
                'last_name_kana' => 'イワモト',
                'first_name_en' => 'koudai',
                'last_name_en' => 'iwamoto',
                'graduation_year' => null,
                'grade' => 1,
                'position_id' => 2,
                'prefecture_id' => 24,
                'alma_mater' => '三重県三重高等学校',
                'achievement' => 'インターハイ個人戦 ベスト32',
            ],
            [
                'user_id' => 61,
                'first_name_ja' => '友志',
                'last_name_ja' => '両角',
                'first_name_kana' => 'ユウシ',
                'last_name_kana' => 'モロズミ',
                'first_name_en' => 'yushi',
                'last_name_en' => 'morozumi',
                'graduation_year' => null,
                'grade' => 1,
                'position_id' => 2,
                'prefecture_id' => 13,
                'alma_mater' => '奈良県高田商業高等学校',
                'achievement' => '近畿インドア個人戦 第3位',
            ],
            [
                'user_id' => 62,
                'first_name_ja' => '倫太朗',
                'last_name_ja' => '濱田',
                'first_name_kana' => 'リンタロウ',
                'last_name_kana' => 'ハマダ',
                'first_name_en' => 'rintarou',
                'last_name_en' => 'hamada',
                'graduation_year' => null,
                'grade' => 1,
                'position_id' => 1,
                'prefecture_id' => 17,
                'alma_mater' => '奈良県高田商業高等学校',
                'achievement' => '近畿インドア個人戦 第9位',
            ],
            [
                'user_id' => 63,
                'first_name_ja' => '康平',
                'last_name_ja' => '幡谷',
                'first_name_kana' => 'コウヘイ',
                'last_name_kana' => 'ハタヤ',
                'first_name_en' => 'kouhei',
                'last_name_en' => 'hataya',
                'graduation_year' => null,
                'grade' => 1,
                'position_id' => 1,
                'prefecture_id' => 11,
                'alma_mater' => '奈良県高田商業高等学校',
                'achievement' => 'JOC杯 U17 シングルス優勝',
            ],
            [
                'user_id' => 64,
                'first_name_ja' => '祐',
                'last_name_ja' => '濱田',
                'first_name_kana' => 'ユウ',
                'last_name_kana' => 'ハマダ',
                'first_name_en' => 'yu',
                'last_name_en' => 'hamada',
                'graduation_year' => null,
                'grade' => 1,
                'position_id' => 1,
                'prefecture_id' => 30,
                'alma_mater' => '和歌山県和歌山北高等学校',
                'achievement' => 'インターハイ出場',
            ],
            [
                'user_id' => 65,
                'first_name_ja' => '翼',
                'last_name_ja' => '高田',
                'first_name_kana' => 'ツバサ',
                'last_name_kana' => 'タカタ',
                'first_name_en' => 'tsubasa',
                'last_name_en' => 'takata',
                'graduation_year' => null,
                'grade' => 1,
                'position_id' => 2,
                'prefecture_id' => 16,
                'alma_mater' => '富山県高岡商業高等学校',
                'achievement' => '2019 茨城国体少年男子 第7位',
            ],
        ]);
    }
}
